// <auto-generated />
namespace Rozmawiator.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CallRequestTimestamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CallRequestTimestamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201606061521288_CallRequestTimestamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
